version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: checklists_db
    restart: always
    environment:
      POSTGRES_DB: checklists_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
