services:
  db:
    image: postgres:16.3-alpine
    container_name: checklists_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "54320:5432"
    volumes:
      - checklists_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  migrations:
    image: polipak/checklists_backend:dev
    container_name: checklists-migrations
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: python manage.py migrate --noinput

  backend:
    image: polipak/checklists_backend:dev
    container_name: checklists-backend
    restart: unless-stopped
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    depends_on:
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env

  nginx:
    image: nginx:1.25
    container_name: checklists-nginx
    restart: unless-stopped
    ports:
      - "8700:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/
    depends_on:
      - backend


volumes:
  checklists_pgdata:
  static_volume:
  media_volume: