services:
  db:
    image: postgres:16.3-alpine
    container_name: checklists_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: