# Generated by Django 5.2.16 on 2026-07-31 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_uid', models.CharField(db_index=True, max_length=255, verbose_name='UID-оборудования')),
                ('checklist_type', models.CharField(choices=[('INSPECTION', 'Осмотр'), ('ACCEPTANCE', 'Приемка'), ('HANDOVER', 'Сдача')], max_length=50, verbose_name='Тип чек-листа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон чек-листа',
                'verbose_name_plural': 'Шаблоны чек-листов',
                'unique_together': {('equipment_uid', 'checklist_type')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_uid', models.CharField(db_index=True, max_length=255, verbose_name='UID Оборудования')),
                ('user_uid', models.CharField(db_index=True, max_length=255, verbose_name='UID Пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='checklists.template')),
            ],
            options={
                'verbose_name': 'Результат чек-листа',
                'verbose_name_plural': 'Результаты чек-листов',
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('STRING', 'Строка'), ('INTEGER', 'Целое число'), ('CHOICE', 'Выбор из списка'), ('CHECKBOX', 'Чекбокс'), ('AUTO', 'Автозаполняемое значение')], max_length=20, verbose_name='Тип поля')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='checklists.template')),
            ],
            options={
                'verbose_name': 'Поле шаблона',
                'verbose_name_plural': 'Поля шаблонов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение варианта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='checklists.templatefield')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Текст ответа')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklists.checklistsresult')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='checklists.templatefield')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'unique_together': {('result', 'field')},
            },
        ),
    ]
