# Generated by Django 5.2.16 on 2026-08-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_uid', models.CharField(db_index=True, max_length=36, verbose_name='UID-оборудования')),
                ('checklist_type', models.CharField(choices=[('INSPECTION', 'Осмотр'), ('ACCEPTANCE', 'Приемка'), ('HANDOVER', 'Сдача')], max_length=50, verbose_name='Тип чек-листа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deprecated', models.BooleanField(default=False, verbose_name='Устаревший')),
            ],
            options={
                'verbose_name': 'Шаблон чек-листа',
                'verbose_name_plural': 'Шаблоны чек-листов',
            },
        ),
        migrations.CreateModel(
            name='ChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=255, verbose_name='UID Пользователя')),
                ('shift_number', models.CharField(choices=[('DAY', 'Дневная'), ('NIGHT', 'Ночная')], max_length=10, null=True, verbose_name='Номер смены')),
                ('shift_time', models.DateTimeField(null=True, verbose_name='Время смены')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('is_deprecated', models.BooleanField(default=False, verbose_name='Устаревшая версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='checklists.checklistresult', verbose_name='Оригинальная анкета')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='checklists.template')),
            ],
            options={
                'verbose_name': 'Результат чек-листа',
                'verbose_name_plural': 'Результаты чек-листов',
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('STRING', 'Строка'), ('INTEGER', 'Целое число'), ('CHOICE', 'Выбор из списка'), ('CHECKBOX', 'Чекбокс'), ('AUTO', 'Автозаполняемое значение')], max_length=20, verbose_name='Тип поля')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательное поле')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='checklists.template')),
            ],
            options={
                'verbose_name': 'Поле шаблона',
                'verbose_name_plural': 'Поля шаблонов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение варианта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='checklists.templatefield')),
            ],
            options={
                'verbose_name': 'Вариант выбора',
                'verbose_name_plural': 'Варианты выбора',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения группы')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='checklists.template')),
            ],
            options={
                'verbose_name': 'Группа полей',
                'verbose_name_plural': 'Группы полей',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='templatefield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='checklists.templatefieldgroup'),
        ),
        migrations.CreateModel(
            name='ChecklistSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OPERATOR_OUT', 'Сдающий оператор'), ('OPERATOR_IN', 'Принимающий оператор'), ('MASTER', 'Мастер смены')], max_length=20, verbose_name='Роль')),
                ('user_uid', models.CharField(max_length=255, verbose_name='UID Подписанта')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписи')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='checklists.checklistresult')),
            ],
            options={
                'verbose_name': 'Подпись',
                'verbose_name_plural': 'Подписи',
                'constraints': [models.UniqueConstraint(fields=('result', 'role'), name='unique_role_signature_per_result')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Текст ответа')),
                ('comment', models.TextField(null=True, verbose_name='Замечание')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklists.checklistresult')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='checklists.templatefield')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'constraints': [models.UniqueConstraint(fields=('result', 'field'), name='unique_answer_per_result')],
            },
        ),
        migrations.AddConstraint(
            model_name='templatefieldgroup',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_group_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(fields=('group', 'order'), name='unique_field_order_per_group'),
        ),
    ]
