# Generated by Django 5.2.16 on 2026-07-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='equipment_id',
            new_name='equipment_uid',
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('equipment_uid', 'checklist_type')},
        ),
    ]
