# Generated by Django 5.2.17 on 2026-08-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistanswer',
            name='is_violation',
            field=models.BooleanField(default=False, verbose_name='Отклонение (Негативный ответ)'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='has_violations',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Есть отклонения'),
        ),
    ]
