# Generated by Django 5.2.16 on 2026-08-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecklistsResult',
            new_name='ChecklistResult',
        ),
    ]
