# Generated by Django 5.2.16 on 2026-08-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefield',
            name='template',
        ),
    ]
