# Generated by Django 5.2.16 on 2026-08-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_rename_checklistsresult_checklistresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set(),
        ),
    ]
