# Generated by Django 5.2.17 on 2026-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_remove_templatefield_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistsignature',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Составитель'), ('APPROVER', 'Утверждающий (Подписант)'), ('READER', 'Ознакомлен (Читатель)')], max_length=20, verbose_name='Роль'),
        ),
    ]
