# Generated by Django 5.2.17 on 2026-08-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_checklistsignature_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('STRING', 'Строка'), ('INTEGER', 'Целое число'), ('CHOICE', 'Выбор из списка'), ('CHECKBOX', 'Чекбокс'), ('DATE', 'Дата'), ('AUTO DATE', 'Автоматическая дата')], max_length=20, verbose_name='Тип поля'),
        ),
    ]
