# Generated by Django 5.2.17 on 2026-09-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_templatefield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefieldgroup',
            name='page_break',
            field=models.BooleanField(default=False, verbose_name='Разрыв страницы'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Замечание'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='general_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Общий комментарий'),
        ),
    ]
