# Generated by Django 5.2.16 on 2026-08-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_template_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldchoice',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Вариант выбора', 'verbose_name_plural': 'Варианты выбора'},
        ),
        migrations.RemoveField(
            model_name='checklistresult',
            name='equipment_uid',
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='Устаревший'),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='template',
            name='equipment_uid',
            field=models.CharField(db_index=True, max_length=36, verbose_name='UID-оборудования'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_field_order_per_template'),
        ),
    ]
