# Generated by Django 5.2.17 on 2026-09-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_templatefieldgroup_page_break_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название шаблона'),
        ),
    ]
