# Generated by Django 5.2.17 on 2026-08-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_alter_templatefield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresult',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('STRING', 'Строка'), ('INTEGER', 'Целое число'), ('CHOICE', 'Выбор из списка'), ('CHECKBOX', 'Чекбокс'), ('DATE', 'Дата'), ('AUTO_DATE', 'Автоматическая дата')], max_length=20, verbose_name='Тип поля'),
        ),
    ]
