# Generated by Django 5.2.16 on 2026-08-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_alter_fieldchoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresult',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='Устаревшая версия'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='checklists.checklistresult', verbose_name='Оригинальная анкета'),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательное поле'),
        ),
    ]
