# Generated by Django 5.2.16 on 2026-08-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_checklistresult_is_deprecated_checklistresult_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistanswer',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='shift_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Номер смены'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='shift_time',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Время смены'),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Группа полей'),
        ),
        migrations.CreateModel(
            name='ChecklistSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OPERATOR_OUT', 'Сдающий оператор'), ('OPERATOR_IN', 'Принимающий оператор'), ('MASTER', 'Мастер смены')], max_length=20, verbose_name='Роль')),
                ('user_uid', models.CharField(max_length=255, verbose_name='UID Подписанта')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписи')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='checklists.checklistresult')),
            ],
            options={
                'verbose_name': 'Подпись',
                'verbose_name_plural': 'Подписи',
                'unique_together': {('result', 'role')},
            },
        ),
    ]
