# Generated by Django 5.2.17 on 2026-08-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_checklistresult_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresult',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='general_comment',
            field=models.TextField(null=True, verbose_name='Общий комментарий'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='source_service',
            field=models.CharField(max_length=100, null=True, verbose_name='Система источник'),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные (Фронтенд)'),
        ),
    ]
