# Generated by Django 5.2.17 on 2026-09-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_remove_checklistsignature_unique_role_signature_per_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchoice',
            name='is_violation',
            field=models.BooleanField(default=False, verbose_name='Считается отклонением'),
        ),
    ]
